
export const courts = [
    {
      id: "home-test-court",
      name: "Home Test Court",
      address: "324 N Main Street, Statesboro, GA",
      city: "Statesboro",
      state: "GA",
      country: "USA",
      latitude: 32.4487,
      longitude: -81.7832,
      radius: 400, // meters
    },
    {
      id: "savannah-downtown",
      name: "Forsyth Park Court",
      address: "Drayton St & W Gaston St, Savannah, GA",
      city: "Savannah",
      state: "GA",
      country: "USA",
      latitude: 32.071,
      longitude: -81.095,
      radius: 400,
    },
    {
      id: "atlanta-piedmont-park",
      name: "Piedmont Park Active Oval",
      address: "1320 Monroe Dr NE, Atlanta, GA",
      city: "Atlanta",
      state: "GA",
      country: "USA",
      latitude: 33.785,
      longitude: -84.373,
      radius: 400,
    },
    {
      id: "augusta-riverwalk",
      name: "Augusta Riverwalk Court",
      address: "10th St, Augusta, GA",
      city: "Augusta",
      state: "GA",
      country: "USA",
      latitude: 33.474,
      longitude: -81.96,
      radius: 400,
    },
    {
      id: "columbus-uptown",
      name: "Woodruff Park Court",
      address: "1000 Bay Ave, Columbus, GA",
      city: "Columbus",
      state: "GA",
      country: "USA",
      latitude: 32.464,
      longitude: -84.994,
      radius: 400,
    },
    {
      id: "macon-central-city",
      name: "Central City Park",
      address: "115 Willie Smokie Glover Dr, Macon, GA",
      city: "Macon",
      state: "GA",
      country: "USA",
      latitude: 32.844,
      longitude: -83.642,
      radius: 400,
    },
    {
      id: "athens-bishop-park",
      name: "Bishop Park Courts",
      address: "705 Sunset Dr, Athens, GA",
      city: "Athens",
      state: "GA",
      country: "USA",
      latitude: 33.94,
      longitude: -83.395,
      radius: 400,
    },
    {
      id: "roswell-area-park",
      name: "Roswell Area Park Courts",
      address: "10495 Woodstock Rd, Roswell, GA",
      city: "Roswell",
      state: "GA",
      country: "USA",
      latitude: 34.053,
      longitude: -84.37,
      radius: 400,
    },
    {
      id: "albany-tift-park",
      name: "Tift Park",
      address: "1200 N Monroe St, Albany, GA",
      city: "Albany",
      state: "GA",
      country: "USA",
      latitude: 31.591,
      longitude: -84.159,
      radius: 400,
    },
    {
      id: "warner-robins-perkins",
      name: "Perkins Field",
      address: "105 Mulberry St, Warner Robins, GA",
      city: "Warner Robins",
      state: "GA",
      country: "USA",
      latitude: 32.618,
      longitude: -83.626,
      radius: 400,
    },
    {
      id: "alpharetta-north-park",
      name: "North Park",
      address: "13450 Cogburn Rd, Alpharetta, GA",
      city: "Alpharetta",
      state: "GA",
      country: "USA",
      latitude: 34.131,
      longitude: -84.278,
      radius: 400,
    },
    {
      id: "marietta-laurel-park",
      name: "Laurel Park",
      address: "1515 Tumlin St SW, Marietta, GA",
      city: "Marietta",
      state: "GA",
      country: "USA",
      latitude: 33.942,
      longitude: -84.566,
      radius: 400,
    },
    {
      id: "gainesville-longwood",
      name: "Longwood Park",
      address: "2033 Longwood Dr, Gainesville, GA",
      city: "Gainesville",
      state: "GA",
      country: "USA",
      latitude: 34.321,
      longitude: -83.829,
      radius: 400,
    },
    {
      id: "valdosta-mccracken",
      name: "McCracken Pocket Park",
      address: "425 S Lee St, Valdosta, GA",
      city: "Valdosta",
      state: "GA",
      country: "USA",
      latitude: 30.825,
      longitude: -83.279,
      radius: 400,
    },
    {
      id: "brunswick-howard-coffin",
      name: "Howard Coffin Park",
      address: "1402 Lanier Blvd, Brunswick, GA",
      city: "Brunswick",
      state: "GA",
      country: "USA",
      latitude: 31.162,
      longitude: -81.493,
      radius: 400,
    },
    {
      id: "dalton-brookwood",
      name: "Brookwood Park",
      address: "1329 Westcott Ave, Dalton, GA",
      city: "Dalton",
      state: "GA",
      country: "USA",
      latitude: 34.786,
      longitude: -84.995,
      radius: 400,
    }
  ];
